pipeline:
  install:
    image: node:8.12.0
    commands:
      - node --version
      - yarn --version
      - yarn install
    when:
      branch: [ master, develop ]
      event: [ push, pull_request ]

  testing:
    image: node:8.12.0
    commands:
      - yarn run test
    when:
      branch: [ master, develop ]
      event: [ push, pull_request ]


  deploy:
    image: plugins/docker
      settings:
        username: jack828
        password: "bBWvS&q4TwGa&peZ!SuXRj#LRx*T@o3MR!*2nw2OS2"
        repo: jack828/jackburgess.dev
        tag: latest
    when:
      branch: master
